로또 게임 미션 리뷰 요청 드립니다!
banjjoknim/java-lotto-game pull request #2
Opened 2021-04-09 07:44 UTC by banjjoknim

먼저, 이전에 리뷰를 진행했던 시점과, 현재 시점이 상당 시간 공백이 있었기 때문에, 처음부터 다시 미션을 진행했습니다. 또, 이전에 PR했던 브랜치인 `feature` 를 바탕으로 진행했기 때문에 상당 부분 비슷하다고 느끼실 수도 있을 것 같습니다. 물론, 이전에 받았던 리뷰들을 반영하고자 노력하였습니다.

새롭게 미션을 진행하면서 특정 클래스(`LottoNumber`, `Lotto`)의 `equals` 및 `toString` 메서드를 `override` 해서 사용했는데, 이 부분에 대해서 사실상 처음으로 `override`해서 사용한 것이기에 이렇게 사용해도 되는 것인지, 그리고 적절한 처사였는지 궁금합니다.

늘 정성껏 리뷰해주셔서 감사합니다.

2021-04-10 07:59 UTC, Rok93 reviewed
코멘트가 엄청 많아서 부담되실 수도 있지만, 이것저것 잔 피드백이나 그냥 눈으로만 훑고 지나가도 되는 코멘트가 많아서 너무 걱정 안하셔도 될 것 같습니다 😉🤔 . 

이번 피드백의 가장 큰 핵심은 ``테스트하기 힘든 코드를 어떻게 테스트할 것인가?`` 이고, 이에 대한 해결책은 참고자료로 대체하였습니다. 두 참고자료가 많이 도움이 될 것 같아요 💪💪💪. 

테스트하기 힘든 코드를 개선하면 더 테스트할 수 있는 영역들이 생겨날거고, 다음 리뷰때 테스트 코드는 조금 더 자세하게 들여다 보는걸로 할게요!  (테스트 코드 쪽은 보지도 않았는데 벌써 코멘트가 30개나 쌓여서... 너무 한번에 과하게 피드백을 드린게 아닌가 싶네요 😅 다음부터는 완급조절 하겠습니다 👏👏👏) 

테스트 코드부분은 피드백 수정하고 나면 바뀔 부분들이 꽤 있을거라는 생각이 드네요 👀, 그래서 피드백 반영한 뒤에 다시 제대로 보는 걸로 할게요! 

궁금한 사항은 언제든 코멘트나 카톡 연락 주시면 될 것 같습니다 🤙 .

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Rank.java
> +    public static Rank getRank(int matchCount, boolean hasBonusNo) {
``getRank`` 메서드 명만 봤을 때, 해당 기능이 어떤 기능인지 그 의도를 바로 파악하기 힘들 것 같아요! 
네이밍에 대해 조금 더 고민해보면 어떨까요?

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Rank.java
> +                .orElseGet(() -> Rank.NONE);
```suggestion
               .orElse(Rank.NONE);
```

인텔리제이도 추천하고 있지만, 위와 같이 변경해보면 어떨까 싶어요!   
단지 ``orElse``를 사용할 때는 주의가 필요하다는 점 [참고자료](http://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/) 의 2번 주제를 읽어보시면 좋을 것 같아요! 
겸사겸사 참고자료의 다른 문항들도 같이 읽어보고 Optional을 바르게 쓰는 방법을 숙지하면 좋을 것 같아요 😉

왜 제가 이렇게 고치라고 했는지에 대해서도 코멘트에 추가로 코멘트 달아주시면 좋을 것 같아요 ~!

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Rank.java
> +        return ranks.stream()
```suggestion
        }
        
        return ranks.stream()
```
if 분기문 다음에는 한줄 띄는게 코드 컨벤션입니다.

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Money.java
> +    private final BigDecimal amount;
BigDecimal 사용 👍

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Money.java
> +        if (amount.compareTo(BigDecimal.ZERO) < ZERO) {
``ZERO`` 라는 의미가 약간 모호한 것 같아요. 
``compareTo`` 은  A > B, A == B, A < B 인 경우 각각 1, 0, -1 의 값이 나오는데, 

```suggestion
        if (amount.compareTo(BigDecimal.ZERO)  != -1) {
```
개인적인 의견이지만 위와 같이 변경해서, -1을 상수로 추출하여 의미있는 네이밍을 부여한다면? 조금 더 의미가 와닿지 않을까요 🤔?

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Money.java
> +    private void validateMoney(BigDecimal amount) {
메서드가 배치되는 순서 또한 가독성에 영향을 미칩니다. 
validateMoney의 경우 생성자에서 유효성을 검증할 때 쓰이는 로직입니다. 
``getAmount``보다 위에 위치하는게 더 좋겠죠 😁 ? 

그리고 일반적으로 getter는 최하단으로 내립니다.

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/LottoNumber.java
> +    }
이 부분은 [이펙티브 자바 - 아이템 11 (equals를 재정의하려거든 hashCode도 재정의하라](https://rok93.tistory.com/entry/%EC%95%84%EC%9D%B4%ED%85%9C11-equals%EB%A5%BC-%EC%9E%AC%EC%A0%95%EC%9D%98%ED%95%98%EB%A0%A4%EA%B1%B0%EB%93%A0-hashCode%EB%8F%84-%EC%9E%AC%EC%A0%95%EC%9D%98%ED%95%98%EB%9D%BC) 을 참고해서 hashCode도 같이 정의해주세요!

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Lotto.java
> +    private void validateLottoNumbers(List<LottoNumber> numbers) {
``validateLottoNumbers`` 호출되는 순서상 가 ``generatorLottoNumbers`` 보다 위에 있는게 좋겠죠!? 😉

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/LottoNumber.java
> +public class LottoNumber {
자주 쓰이는 LottoNumber를 미리 캐싱해뒀다가 필요할 때마다 캐싱해놓은 값을 꺼내서 사용해보는건 어떨까요 ?  😁

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Lotto.java
> +    }
이 코드는 View에 의존하는 코드입니다. 
클라이언트(View단)가 요청하는 스펙에 따라 변경이 발생한다는 것인데, MVC 패턴을 생각했을 때, View의 변화가 Model에 영향을 미친다는 것인데, 이는 MVC 패턴에 어긋나는 상황이겠죠?

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Lotto.java
> +    public List<LottoNumber> getNumbers() {
``getter``, ``setter``는 최하단으로 내리는게 좋습니다.  (equals & hashCode 혹은 compareTo 를 재정의 했을 경우 이 코드 가 가장 하단에 내려가야합니다)

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Lotto.java
> +    }
``String 문자열``을  ``Lotto``로 변경하는 역할은 누구의 책임일까요? 

제 생각에는 InputView 에서는 ``원시 값``(ex. 문자열)을 받아오는 것이 좋다고 생각해요! 
뷰에서 받은 원시값을 가지고 컨트롤러에서 도메인 객체를 생성하는 것이 좋다고 생각합니다.

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Lotto.java
> +                .count();
``distinct``로 중복된 값을 제거하는 방법도 있겠지만, ``Set`` 자료구조 특성을 이용해서 HashSet 과 List의 길이를 비교하는 방법도 있다는 점 정도로 언급하고 지나갈게요! 물론 Set으로 비교하는 경우에도 LottoNumber의 equals & hashCode 재정의는 필요합니다. 😉  



이 부분은 본인 스타일대로 가도 상관없다고 생각하니 변경하지 않으셔도 좋습니다!

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Lotto.java
> +                .mapToInt(number -> number.getNumber())
LottoNumber가 제대로된 VO 객체라면 mapToInt는 빠져도 정상적으로 동작할거에요! 
하지만 지금 코드에서는 이 코드를 제거하면 이 예외처리와 관련된 테스트가 실패하게되요! 
왜 그럴까요!?  

중요한 개념 중 하나이니, 꼭 아래의 내용을 읽어보시고 지금 코드에서 어떤 점을 개선해야 ``mapToInt``를 제거할 수 있을지 생각해보면 좋을 것 같아요 🤔
[VO(Value Ojbect)란 무엇일까?](https://woowacourse.github.io/javable/post/2020-06-11-value-object/)

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Lotto.java
> +    public static Lotto generateLottoByInput(String inputLottoNumbers) {
``정적 팩토리 메서드`` 는 생성자의 다음 위치에 있어야 합니다. 

메서드, 생성자, 정적 팩토리 메서드, private 메서드 등의 배치도 가독성에 영향을 미칩니다. 
다음 PR 전에는 배치도 고려해서 리팩토링해보셨으면 좋겠습니다 👍

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/LottoNumber.java
> +        validateNumberIsValid(number);
``validateNumberIsValid`` 는 어색한 메서드명인거 같아요. 
'유효한 값인가'가 유효하다 ?   valid valid가 이중으로 붙어서 그런것 같아요 😅 

``validateNumberIsPositive``도 이런 표현보다는 ``validatePositiveNumber`` 와 같이 표현하는게 좋지 않을까요? 
``validateNumberIsValid`` 의 네이밍도 적절하게 변경해보죠!! 💪

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/LottoNumber.java
> +            throw new IllegalArgumentException(LOTTO_NUMBER_MUST_BETWEEN_ONE_AND_FORTY_FIVE);
이 얘기는 가볍게 봐주세요 ~ 👀 👀

``LOTTO_NUMBER_MUST_BETWEEN_ONE_AND_FORTY_FIVE`` 에서  ONE, FORTY_FIVE 와 같이 정확한 값을 지칭하는 것은 변경이 발생할 때마다 번거로워지는 단점이 있어요. 

조건문에 쓰인 ``MIN_LOTTO_NUMBER``, ``MAX_LOTTO_NUMBER`` 와 같이 로또 넘버의 최소, 최대 숫자값이 바뀌더라도 상수명의 변경은 없도록 하는게 변화에 더 유연하게 대처할 수 있을거에요! (지금 로또 게임과 같은 경우는 변경될 일이 없다는 확신이 있기 때문에 크게 문제는 안된다고 봐요! 가볍게 알고 지나가면 좋겠다는 생각에 코멘트 달았어요~ )

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/LottoNumber.java
> +    }
랜덤 값을 생성하는 이 로직을 다른 클래스로 분리해보는건 어떨까요?
지금 ``LottoNumber - generateRandomNumber()`` ->  ``Lotto - generateLottoNumbers()`` -> ``Lottos ->generateLottos``  로 이어지는데  이는 모두 ``테스트하기 어려운 Random 요소에 의존``하고 있다는 것입니다. 
당연하게도 테스트가 없거나 혹은 있더라도 값을 제어할 수없어서 빈약한 테스트 코드를 작성할 수 밖에 없을거라고 추측합니다. 
(ex. 값이 0~ 45 사이의 값인지 확인한다거나 길이나 사이즈가 6이라거나 etc..) 

``테스트하기 힘든 코드를 최대한 밖으로 `` 꺼냄으로써 테스트할 수 있는 영역을 확보해가려고 하는데, 사실 이전에도 언급했던 적이 있는데 조금 어려워하셨던 기억이나네요 (어려운 내용 맞습니다)😂  어떻게 전달할지 고민해보다가 좋은 영상이나 자료를 전달드리는게 가장 빠른 길이다 싶어서 아래에 좋은 참고자료들을 가져왔습니다! 

앞에서 언급한 ``테스트하기 힘든 코드를 최대한 밖으로 꺼내서 테스트할 수 있는 영역을 확보해나간다`` 라는 표현이 와닿으셨으면 좋겠네요. 

일단 제가 의도하는 방향은 최종적으로 Lottos를 생성하는 핵심 기능을 외부로 분리하게 하려는 것입니다. 
먼저 이 의도를 먼저 머릿속으로 생각하시면서 참고자료를 보시면 좋을 것 같아요! 
잘 모르겠다면 코멘트에 추가 질문 남겨주세요 ~

[참고자료]
* [인터페이스를 분리하여 테스트하기 좋은 메서드로 만들기](https://woowacourse.github.io/javable/post/2020-05-17-appropriate_method_for_test_by_interface/) 
*  [무엇을 테스트할 것인가? 어떻게 테스트할 것인가? (권용근) ](https://youtu.be/YdtknE_yPk4?t=639)

용근님의 발표 내용이 개인적으로 쉽게 와닿았던 것 같아서 이 내용을 참고해보면 이해에 도움이 되실 것 같아요!  제가 전달하고자 하는 내용은 ``2번째 주제(테스트 가능한 것, 불가능한 것)``인데 해당 내용만 보셔도 됩니다만 다른 내용도 관심이 있다면 쭉 보셔도  상관없어요~

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Lottos.java
> +                .intValue();
getter로 값을 꺼내서 로직을 처리하지 말고 money 객체에게 메세지를 보내는건 어떨까요?

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Lotto.java
> +    public static List<LottoNumber> generateLottoNumbers() {
굳이 여기서 ``List<LottoNumber>`` 타입을 리턴하지 말고 바로 ``Lotto``를 리턴해주는게 좋지 않을까요?

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Lottos.java
> +    public Map<Rank, Integer> getStatistics(WinningLotto winningLotto) {
``getStatistics`` 보다 더 좋은 네이밍을 고려해보셨으면 좋겠어요 🤔

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/WinningLotto.java
> +        if (lotto.getNumbers().contains(bonusNo)) {
lotto의 LottoNumbers를 꺼내서 bonusNo가 포함되었는지 확인하는 것이 아니라, 메세지를 보내보면 어떨까요? 
Lotto에 ``hasNumber()`` 라는 메서드가 이미 정의되어있어요!

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/WinningLotto.java
> +                .count();
이 또한 lotto에게 메세지를 보내는 구조로 변경할 수 있을것 같네요. 
이런 구조가 자주 보이는데 이는 [디미터의 법칙](https://woowacourse.github.io/javable/post/2020-06-02-law-of-demeter/)을 어기는 것입니다. 디미터의 법칙이 무엇인지 보고오면 좋을 것 같아요!

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Lottos.java
> +        BigDecimal totalSpendMoney = new BigDecimal(lottos.size() * LOTTO_PRICE);
처음에 로또를 구매하기 위해 구입금액을 입력받았는데, 다시 lottos의 크기를 가지고 구입금액을 구하는 작업을 하고있습니다. 
비효율적이라는 생각이 드네요. 

처음에 입력한 구입금액을 Controller에 변수로 받아뒀다가 그 값을 ``calculateYield()`` 메서드 파라미터로 받아오는게 낫지 않을까요?

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Lottos.java
> +                .mapToLong(rank -> statistics.get(rank) * rank.getWinningMoney())
```suggestion
               .mapToLong(rank -> rank.calculateBenefit(statistics.get(rank)))
```
rank에 메세지를 보내는 구조로 변경해볼까요 ?? 🤩

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Rank.java
> +        ArrayList<Rank> ranks = new ArrayList<>(Arrays.asList(Rank.values()));
```suggestion
        List<Rank> ranks = new ArrayList<>(Arrays.asList(Rank.values()));
```

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/Rank.java
> +    public static Rank getRank(int matchCount, boolean hasBonusNo) {
나쁘지 않은 방식이고 로직상에도 문제가 없지만, 매번 호출될 때 마다 List를 생성하고 삭제하는 작업을 반복하는 것이 비효율적이라는 생각이 드네요.

```java
public static LottoRank isMatch(int correctCnt, boolean isBonusMatch) {
    if (SECOND.matchCount(correctCnt) || THIRD.matchCount(correctCnt)) {
        return determineSecondOrThird(isBonusMatch);
    }

        return Arrays.stream(LottoRank.values())
                .filter(lottoRank -> lottoRank.matchCount(correctCnt))
                .findAny()
                .orElse(MISS);
}

private static LottoRank determineSecondOrThird(boolean isBonusMatch) {
    if (isBonusMatch) {
        return SECOND;
    }

    return THIRD;
}
```

예를들어 이런 구조는 어떨까요?

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/model/WinningLotto.java
> +    public WinningLotto(Lotto lotto, LottoNumber bonusNo) {
실제로 사용되는 WinningLotto를 생성하는 로직은 정적 팩토리 메서드인 ``issueWinningLotto()`` 만 사용되는 것 같습니다. 
생성자를 public으로 열어두는 것은 코드를 사용해야하는 개발자들에게 혼란을 줄 수 있습니다.  외부에서 사용하지 않은 생성자라면 접근제어자를 private로 변경해주세요~!  😉

WinningLotto를 생성하는 케이스는 하나뿐인데 굳.이 정적 팩토리 메서드를 쓸 필요가 있을까? 라는 생각이 먼저 드네요.
[정적 팩토리 메서드](https://woowacourse.github.io/javable/post/2020-05-26-static-factory-method/) 내용을 고려했을 때, 어떤 의도로 ``issueWinningLotto()`` 정적 팩토리 메서드를 쓴 것인지 알려주시겠어요 🤔 ?

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/view/OutputView.java
> +    }
파라미터로 int 타입이 아닌 Rank 타입을 받아오면 추상화가 가능하지 않을까 싶어요 🤔 ! 
단지 2등의 경우 "보너스 볼 일치" 라는 특별한 코멘트가 추가되기 때문에 Rank.SECOND일 경우만 예외로 따로 메서드를 만들어도 좋을 것 같네요. 

``printWinningCounts`` 에서 반복문으로 처리할 수 있을 것 같아요!  (물론 for문 안에 if 조건문이 붙으면서 depth가 초과하겠지만... view 단은 예외적으로 depth 요구사항을 지키지 않으셔도 무방합니다)

2021-04-10 07:59 UTC, Rok93 commented on src/main/java/view/OutputView.java
> +        printYield(lottos.calculateYield(winningLotto));
View단에서 도메인 로직이 수행되고 있어요 😱 ! 
``getStatistics()``, ``calculateYield(winningLotto``는 컨트롤러단에서 수행되고 그 결과들을 파라미터로 받아와서 출력해줘야 한다고 생각해요!

2021-04-10 07:59 UTC, Rok93 commented on src/test/java/model/LottoNumberTest.java
> +        assertThatThrownBy(() -> new LottoNumber(number))
저도 given when then 구조 꼭 만들어서 테스트하는 입장으로 구조를 지켜주신 점에서는 마음의 안정을 느꼈습니다. 
소소한 팁이지만, 예외 테스트의 경우 when 절이 조금 애매해지는 경우가 있습니다. 
저 같은 경우 이런 경우 아래와 같이 작성합니다.
```suggestion
        // when // then
        assertThatThrownBy(() -> new LottoNumber(number))
```

추가적으로 ParameterizedTest 를 하는 경우 given 상황이 미리 주어지는 경우가 잦기 때문에 이런 경우에는 //given을 명시하지 않고있습니다. 

(이는 컨벤션 같은게 아니라 제 개인적인 코딩 스타일 이라는 점! 참고만 해주세요)

2021-04-10 07:59 UTC, Rok93 commented on src/test/java/model/LottosTest.java
> +    }
@BeforeEach 애너테이션을 따로 2개 추가하는 것 보다는 아래와 같이 바꾸는게 좋지 않을까요? 

```java
    @BeforeEach
    void setUp() {
        setUpWinningLotto();
        setUpLottos();
    }
```
물론 두 메서드의 @BeforeEach 애너테이션은 제거된 상태입니다. 

코드를 처음 보는 사람 입장에서, 테스트를 위해 초기 셋팅하는 값이 이리저리 분산되어있으면 코드 파악하기가 매우 어렵습니다. 😭

2021-04-10 07:59 UTC, Rok93 commented on src/test/java/model/LottosTest.java
> +        assertThat(statistics.get(Rank.FIFTH)).isEqualTo(1);
하나의 테스트코드에서 여러 테스트를 동시에 진행할 경우에는 가급적 ``assertAll()`` 을 사용해주는 것이 좋습니다.

2021-04-10 07:59 UTC, Rok93 commented on src/test/java/model/LottoNumberTest.java
> +    @ValueSource(ints = {46, 49, 77, 56, 99, 0})
이건 개인적인 의견이지만, 오름차순 혹은 내림차순으로 일관되게 value 들을 작성해주는게 가독성에 좋다고 생각합니다. 
```suggestion
    @ValueSource(ints = {0, 46, 49, 77, 56, 99})
```

2021-04-10 07:59 UTC, Rok93 commented on src/test/java/model/LottoNumberTest.java
> +    @ValueSource(ints = {1, 45, 37, 38, 27})
이 또한 어짜피 각 value들이 독립적인 테스트를 진행하기 때문에 오름차순 or 내림차순으로 배치해주는 것이 좋은 것 같아요 😁

2021-04-10 07:59 UTC, Rok93 commented on src/test/java/model/LottoTest.java
> +    private List<LottoNumber> setUpLottoNumbers() {
이런 private 메서드는 실제로 호출되는 위치에 가까이 있어야 합니다. 
지금 같은 경우 해당 테스트 클래스의 가장 한단의 두 메서드에서 이 메서드가 호출되고있는데, 위 아래로 왔다갔다 하게 되네요 😭😅

2021-04-10 07:59 UTC, Rok93 commented on src/test/java/model/RankTest.java
> +    }
```java 
    @ParameterizedTest
    @EnumSource(
            value = Rank.class,
            names = {"SECOND", "THIRD"},
            mode = Mode.EXCLUDE)
    void getRankExcludeSecondAndThird(Rank rank) {
        // when
        Rank getRank = Rank.getRank(rank.getMatchCount(), true);

        // then
        assertThat(getRank).isEqualTo(rank);
    }
```

이런 식으로 ``@EnumSource``를 이용해서 bonusball 에 관계없이 결정나는 값들만 추출해서 검증해볼 수도 있을 것 같아요! 
``@MethodSource``도 괜찮을 것 같구요!

[참고자료](https://gmlwjd9405.github.io/2019/11/27/junit5-guide-parameterized-test.html)

2021-04-10 10:47 UTC, banjjoknim commented on src/main/java/model/Rank.java
> +    public static Rank getRank(int matchCount, boolean hasBonusNo) {
반영하도록 하겠습니다!

2021-04-10 11:07 UTC, banjjoknim commented on src/main/java/model/Rank.java
> +                .orElseGet(() -> Rank.NONE);
이미 생성되었거나 계산된 값은 `orElse`을 사용하는 것이 좋다고 되어있었습니다. 살펴보면서 고민을 해봤더니, `Rank.NONE` 자체는 새롭게 메모리에 할당되어 만들어지는 것이 아닌 이미 존재하는 상수이기 때문에 이미 존재하는 상수를 가져오기 위해 `Supplier`를 가져오는 것은 비효율적이라는 결론에 도달했습니다.

2021-04-10 11:13 UTC, banjjoknim commented on src/main/java/model/Money.java
> +    private final BigDecimal amount;
칭찬 감사합니다.

2021-04-10 12:31 UTC, banjjoknim commented on src/main/java/model/Money.java
> +        if (amount.compareTo(BigDecimal.ZERO) < ZERO) {
고민해서 반영하겠습니다!

2021-04-10 12:37 UTC, banjjoknim commented on src/main/java/model/Money.java
> +    private void validateMoney(BigDecimal amount) {
메서드 배치가 가독성에 미치는 영향은 익히 말씀해주셔서 알고 있었으나, getter의 위치에 대해서는 무지했던 것 같습니다. 반영하도록 하겠습니다.

2021-04-10 13:09 UTC, banjjoknim commented on src/main/java/model/LottoNumber.java
> +    }
좋은 피드백 감사합니다. 유념하도록 하겠습니다.

2021-04-10 13:12 UTC, banjjoknim commented on src/main/java/model/Lotto.java
> +    private void validateLottoNumbers(List<LottoNumber> numbers) {
놓쳤던 부분인 것 같습니다. 반영하도록 하겠습니다!

2021-04-10 13:15 UTC, banjjoknim commented on src/main/java/model/Lotto.java
> +    public List<LottoNumber> getNumbers() {
유념하여 반영하도록 하겠습니다.

2021-04-10 13:19 UTC, banjjoknim commented on src/main/java/model/Lotto.java
> +                .count();
좋은 피드백 감사합니다!

2021-04-10 13:50 UTC, banjjoknim commented on src/main/java/model/Lotto.java
> +                .mapToInt(number -> number.getNumber())
좋은 피드백 감사합니다. 현재 문제점이 `equals`는 재정의 했으나 `hashCode`는 재정의하지 않아서 발생했다는 것을 알게 되었습니다. 참고자료 감사드리며, `VO(Value Object)` 에 대해 유념하도록 하겠습니다.

2021-04-10 13:51 UTC, banjjoknim commented on src/main/java/model/Lotto.java
> +    public static Lotto generateLottoByInput(String inputLottoNumbers) {
좋은 피드백 감사합니다. 반영하도록 하겠습니다!

2021-04-10 13:54 UTC, banjjoknim commented on src/main/java/model/LottoNumber.java
> +        validateNumberIsValid(number);
고민하여 반영하겠습니다.

2021-04-10 13:55 UTC, banjjoknim commented on src/main/java/model/LottoNumber.java
> +            throw new IllegalArgumentException(LOTTO_NUMBER_MUST_BETWEEN_ONE_AND_FORTY_FIVE);
꼼꼼한 피드백 감사합니다 :)

2021-04-10 14:08 UTC, banjjoknim commented on src/main/java/model/Lottos.java
> +                .intValue();
지적 감사합니다. 반영하겠습니다!

2021-04-10 14:50 UTC, banjjoknim commented on src/main/java/model/Lottos.java
> +    public Map<Rank, Integer> getStatistics(WinningLotto winningLotto) {
고민하여 반영해보겠습니다.

2021-04-10 14:51 UTC, banjjoknim commented on src/main/java/model/WinningLotto.java
> +        if (lotto.getNumbers().contains(bonusNo)) {
좋은 피드백 감사합니다.

2021-04-10 15:15 UTC, banjjoknim commented on src/main/java/model/WinningLotto.java
> +                .count();
좋은 참고자료와 피드백 감사합니다! 반영하도록 하겠습니다!

2021-04-10 15:37 UTC, banjjoknim commented on src/main/java/model/Lottos.java
> +                .mapToLong(rank -> statistics.get(rank) * rank.getWinningMoney())
좋은 방향성 제시 감사합니다.

2021-04-10 15:51 UTC, banjjoknim commented on src/main/java/model/Rank.java
> +    public static Rank getRank(int matchCount, boolean hasBonusNo) {
좋은 방향 제시 감사합니다!

2021-04-10 16:15 UTC, banjjoknim commented on src/main/java/model/WinningLotto.java
> +    public WinningLotto(Lotto lotto, LottoNumber bonusNo) {
피드백 감사합니다. 참고하여 반영하도록 하겠습니다.
정신없이 미션을 수행하다보니 놓쳤던 부분인 것 같습니다 ^^..
주의해서 진행하도록 하겠습니다.

2021-04-10 16:26 UTC, banjjoknim commented on src/main/java/view/OutputView.java
> +        printYield(lottos.calculateYield(winningLotto));
피드백 감사합니다!

2021-04-10 16:29 UTC, banjjoknim commented on src/test/java/model/LottoNumberTest.java
> +        assertThatThrownBy(() -> new LottoNumber(number))
좋은 팁 감사합니다 :) 참고하도록 하겠습니다.

2021-04-10 16:31 UTC, banjjoknim commented on src/test/java/model/LottosTest.java
> +    }
코멘트를 보고서 테스트에서도 마찬가지로 적절한 메서드 분리를 해야겠다는 생각이 들었습니다. 피드백 감사합니다!

2021-04-10 16:35 UTC, banjjoknim commented on src/test/java/model/LottosTest.java
> +        assertThat(statistics.get(Rank.FIFTH)).isEqualTo(1);
좋은 방향 제시 감사합니다.

2021-04-10 16:42 UTC, banjjoknim commented on src/test/java/model/LottoNumberTest.java
> +    @ValueSource(ints = {46, 49, 77, 56, 99, 0})
피드백 감사합니다. 반영하도록 하겠습니다!

2021-04-10 16:42 UTC, banjjoknim commented on src/test/java/model/LottoNumberTest.java
> +    @ValueSource(ints = {1, 45, 37, 38, 27})
피드백 감사합니다. 반영하겠습니다!

2021-04-10 16:50 UTC, banjjoknim commented on src/test/java/model/LottoTest.java
> +    private List<LottoNumber> setUpLottoNumbers() {
놓쳤던 부분인 것 같습니다. 반영하도록 하겠습니다!

2021-04-10 17:15 UTC, banjjoknim commented on src/test/java/model/RankTest.java
> +    }
좋은 방향 제시 감사합니다. 적용해보도록 하겠습니다.

2021-04-10 17:28 UTC, banjjoknim commented on src/main/java/model/Lotto.java
> +    }
MVC 패턴에 따라 각각의 역할을 잘 구분해야 하는데, 부족했던 것 같습니다. 적절한 피드백에 감사드립니다 💯

2021-04-10 18:31 UTC, banjjoknim commented on src/main/java/model/Lottos.java
> +        BigDecimal totalSpendMoney = new BigDecimal(lottos.size() * LOTTO_PRICE);
고민하여 적절하게 변경해보도록 노력해보겠습니다!

2021-04-11 01:26 UTC, banjjoknim commented on src/main/java/model/Lotto.java
> +    }
`String 문자열`을 `Lotto`로 변경하는 역할에 대한 책임 소재를 명확히 하는 것이 굉장히 어렵게 느껴졌습니다. `String 문자열`을 `Lotto`에게 주면서 `이걸로 알아서 Lotto가 되어주렴!`이 맞는건지, `InputView`에서 해당 문자열을 친절하게 변환시킨다음 `Lotto야 이걸로 Lotto가 되렴!` 이라고 하는게 맞는건지 구분이 잘 안되는 것 같습니다. 좋은 지침이 있을까요?

2021-04-11 01:44 UTC, banjjoknim commented on src/main/java/view/OutputView.java
> +    }
반영해보도록 하겠습니다!

2021-04-11 02:16 UTC, banjjoknim commented on src/main/java/model/LottoNumber.java
> +public class LottoNumber {
이미 나올 수 있는 경우의 수와 값이 정해져 있는 상황이기 때문에 캐시기능을 이용하기 적합하며 그렇게 하는 것이 성능상으로도 더 효율적인 것 같습니다. 생각지도 못한 부분인데, 피드백 감사합니다!

2021-04-11 20:58 UTC, banjjoknim commented on src/main/java/model/LottoNumber.java
> +    }
자료 참고하여 개선해보도록 하겠습니다, 좋은 참고자료 감사합니다!

2021-04-11 22:45 UTC, banjjoknim commented
먼저, 지난 피드백에 대해 감사하다는 말씀을 드립니다.

그리고 주신 피드백에 대한 질문을 다시 한번 정리해보았습니다.
질문은 크게 2가지 입니다.

---

1. `LottoNumber`
> 코멘트 중에서, Lottos를 생성하는 핵심 기능을 외부로 분리하려는 의도라고 하신게 있었습니다. 그렇다면 여기에서는 Lottos를 생성할 때, Random한 값을 생성하는 부분을 전략으로 분리한 뒤 해당 전략을 테스트함으로써 값의 유효성을 보장한다, 라고 이해하면 되는 것일까요?
>
> 그러니까 핵심은, 테스트하기 어려운(제어하기 힘든) 기능을 최대한 외부로 분리(전략으로 분리)하여 테스트한다. 라는 것 같은데.. 제가 리뷰어님의 의도를 제대로 이해한게 맞는지 여쭤봐도 괜찮을까요? 일단 전략 패턴에 대한 학습이 부족해서 전부 다 이해하지 못한 것 같아 다시 한번 여쭤봅

---

2. `Lotto`
> String 문자열을 Lotto로 변경하는 역할에 대한 책임 소재를 명확히 하는 것이 굉장히 어렵게 느껴졌습니다. String 문자열을 Lotto에게 주면서 이걸로 알아서 Lotto가 되어주렴!이 맞는건지, InputView에서 해당 문자열을 친절하게 변환시킨다음 Lotto야 내가 문자열 바꿔왔어! 이거는 안전한거니까 바로 사용하기만 하면 돼! 이걸로 Lotto가 되렴! 이라고 하는게 맞는건지 구분이 잘 안되는 것 같습니다.
>
> 분명 `Lotto`를 생성하는 책임은 `Lotto`의 것이 맞으나, 그러기 위해서 필요한 과정인 `문자열을 parsing`하고, `List<LottoNumber>` 로 변환하는 과정을 거쳐서 `Lotto`를 생성하게 되는데 `InputView`의 역할은 정말 순수하게 `input`만 하는 것인지, 아니면 `input`된 값의 처리까지도 책임이 있는 것인지 궁금합니다(제가 고민해본 결과, `input`된 값을 검증하고 처리하는 것까지 포함된다고 생각하고 있습니다).
>
>좋은 지침이 있을까요?

---

2021-04-14 06:00 UTC, Rok93 commented on src/main/java/model/Lotto.java
> +    }
제가 표현을 제대로 못한 것 같네요 😅
단지 제가 표현하고 싶었던 의도는 MVC 의 각 역할에서 바라봤을 때, ``Model은 View를 몰라야하고 View는 Model을 몰라야 한다`` 가 핵심이 될 것 같습니다. 

InputView에서 return type으로 도메인 모델 타입을 전달한다는 것은 View가 Model을 이미 알고있다? 라고 생각을 해도 될 것 같습니다. 이에 대한 의존을 끊자는 의미입니다. 

따라서 String 과 같은 원시 값을 받아서 Controller에서 **Lotto와 같은 Model**로 매핑 해주는 것이 적절한 것 같다는 의미였습니다. 
조금 이해가 되셨을까요!? 혹시라도 잘 안 와닿는다면 편하게 물어봐주세요 : )

2021-04-14 06:13 UTC, Rok93 commented on src/main/java/model/LottoNumber.java
> +    }
꼭 ``전략패턴``을 사용해야한다는 것은 아닙니다. 하지만 결론적으로 ``테스트하기 어려운(제어하기 힘든) 기능을 최대한 외부로 분리(전략으로 분리)하여 테스트한다.`` 의 의미는 맞습니다! (용근님이 전달하시려는 의도와 일치하다고 생각해요!)

2021-04-15 02:18 UTC, Rok93 requested changes
질문에 대한 답변을 먼저 드리자면 

1. ``LottoNumber`` 

> 코멘트 중에서, Lottos를 생성하는 핵심 기능을 외부로 분리하려는 의도라고 하신게 있었습니다. 그렇다면 여기에서는 Lottos를 생성할 때, Random한 값을 생성하는 부분을 전략으로 분리한 뒤 해당 전략을 테스트함으로써 값의 유효성을 보장한다, 라고 이해하면 되는 것일까요?

> 그러니까 핵심은, 테스트하기 어려운(제어하기 힘든) 기능을 최대한 외부로 분리(전략으로 분리)하여 테스트한다. 라는 것 같은데.. 제가 리뷰어님의 의도를 제대로 이해한게 맞는지 여쭤봐도 괜찮을까요? 일단 전략 패턴에 대한 학습이 부족해서 전부 다 이해하지 못한 것 같아 다시 한번 여쭤봅니다.

영상을 본지 꽤 오래돼서 정확한 내용이 전부 기억나지는 않지만, 용근님의 의도가 ``테스트하기 어려운(제어하기 힘든) 기능을 최대한 외부로 분리(전략으로 분리)하여 테스트한다.`` 였던걸로 알고있습니다. 제가 전달하고자 했던 의도도 그게 맞습니다. 단지 지금 그 테스트하기 힘든 것이 어떤건지 그 대상을 명확하게 하는 것이 좋을 것 같아요. 저희는 Random한 int형 숫자를 만들고 싶은 것이 아니라, ``Random Lotto``를 만들고 싶은겁니다. 이 관점으로 ``NumberGenerator`` 라는 전략을 만드는 것 보다는 ``LottoGenerator``를 만드는게 더 좋을 것 같아요  😁 
코멘트로 제가 이전에 짯던 코드들도 같이 첨부를 해놨습니다. 코드를 보면 조금 더 와닿지 않을까 싶어요! 

2. ``Lotto``
> String 문자열을 Lotto로 변경하는 역할에 대한 책임 소재를 명확히 하는 것이 굉장히 어렵게 느껴졌습니다. String 문자열을 Lotto에게 주면서 이걸로 알아서 Lotto가 되어주렴!이 맞는건지, InputView에서 해당 문자열을 친절하게 변환시킨다음 Lotto야 내가 문자열 바꿔왔어! 이거는 안전한거니까 바로 사용하기만 하면 돼! 이걸로 Lotto가 되렴! 이라고 하는게 맞는건지 구분이 잘 안되는 것 같습니다.

> 분명 Lotto를 생성하는 책임은 Lotto의 것이 맞으나, 그러기 위해서 필요한 과정인 문자열을 parsing하고, List<LottoNumber> 로 변환하는 과정을 거쳐서 Lotto를 생성하게 되는데 InputView의 역할은 정말 순수하게 input만 하는 것인지, 아니면 input된 값의 처리까지도 책임이 있는 것인지 궁금합니다(제가 고민해본 결과, input된 값을 검증하고 처리하는 것까지 포함된다고 생각하고 있습니다).


이 부분에 대해서는 답변을 드렸습니다만, 다시 한번 언급하자면...  지금 InputView는 Model을 알고 있기에 의존성을 띄고 있고, input된 값의 처리는 InputView의 역할이 아닙니다.  웹 으로 생각을 해봤을 때, HTML 혹은 js로 비동기 통신으로 받아온 값들이 어땠는지 연관지어 생각해보면 도움이 될 것 같아요 🤔 .

input된 값을 검증하는 로직은 클라이언트 단에서도 해야할 일이고 백엔드 단에서도 해야 할 일입니다. (프론트에서 입력값 검증 했으니까 백에서는 처리안해도 되겠지.... 와 같은 생각은 위험하겠죠?  심지어 프론트와 백엔드가 서로 완전히 다른 회사라면? 🤔 아찔하네요  😅) 

단지 저희는 백엔드를 중점적으로 공부하는 것이기에, 프론트에서 꼭 값을 검증하는 로직을 추가하지 않더라도 피드백을 하고 있지는 않습니다.

2021-04-15 02:18 UTC, Rok93 commented on src/main/java/model/Lotto.java
> +            List<LottoNumber> lottoNumbers = Stream.generate(() -> numberGenerator.generate())
```suggestion
            List<LottoNumber> lottoNumbers = Stream.generate(numberGenerator::generate)
```
람다식을 메서드 참조로 변경해볼 수 있을 것 같아요!

2021-04-15 02:18 UTC, Rok93 commented on src/main/java/model/Lotto.java
> +                .filter(number -> winningLotto.hasNumber(number))
```suggestion
                .filter(winningLotto::hasNumber)
```
이 코드 또한 메서드 참조로 변경해볼 수 있을 것 같아요!!

2021-04-15 02:18 UTC, Rok93 commented on src/main/java/model/LottoNumber.java
> +    }
캐싱을 해보라는 의도가 조금 잘못 전달된 것 같네요 : ) 
제가 의도한 바랑은 조금 달라서 [반복적으로 사용되는 인스턴스는 캐싱하기](https://woowacourse.github.io/javable/post/2020-06-24-caching-instance/) 를 참조하시면 캐싱이 어떤 것인지 와닿으실 것 같아요!!  (참고자료에는 직접적인 힌트가 있어서 **보기전에 조금 더 고민해보면 좋을 것 같아요!**) 

지금 (~~캐싱을 한 것이라 추측되는 코드~~) 구조는 특정 number가 absent(= 없는, 부재한)하다면 number를 value로 가지는  LottoNumber를 static 영역에 저장 하고있습니다. 하지만 이는 매번 ``putIfAbsent``를 호출하여 이 값이 ``CACHE`` 에 저장되어있는지 확인하고 있습니다. 이렇게 계속해서 확인하는 것 보다는 CACHE에 미리 ``LottoNumber(1) ~ LottoNumber(45)``를 저장해둔 상태에서 Lottonumber를 CACHE에서 ``get`` 메서드로 가져오는 것이 좋지않을까요!? 

참고자료 내용의 예시가 Lotto 이기 때문에 직접적인 힌트가 될 것같지만, 최대한 생각해보고 본다면 더 큰 도움이 될 것같아요!

2021-04-15 02:18 UTC, Rok93 commented on src/main/java/model/Lotto.java
> +    public static final BigDecimal LOTTO_PRICE = new BigDecimal(1000);
구글 코드 컨벤션에는 이런 내용이 안보이는데..... 
public 메서드를 private 메서드보다 더 위에 명시해주는 것이 좋습니다.

```suggestion
    public static final BigDecimal LOTTO_PRICE = new BigDecimal(1000);
    private static final int LOTTO_SIZE = 6;
    private static final String LOTTO_SIZE_MUST_BE_SIX = "로또 번호는 중복되지 않는 6개의 번호여야 합니다.";
```

2021-04-15 02:18 UTC, Rok93 commented on src/main/java/model/Lotto.java
> +        }
이 try- catch문에는 한 가지 문제점이 있습니다. 물론 확률적으로 희박하겠지만, StackOverflow가 발생할 수 있다는 것인데요. 
중복되는 LottoNumber가 하나라도 발생하면, generateLotto(numberGenereator) 메서드를 재호출하게 될 것입니다. (이런 구조로 코드를 짜더라도 절.대 StackOverFlow가 발생하지 않는다는 확신이 있는 경우라면 다를 수 있지만, 지금 같은 재귀 구조는 조금 위태위태 해보이네요) 

로또를 생성하는 로직 자체를 바꿔볼 수도 있을 것 같고, 혹은 이 부분은 while문을 통해 ``재귀를 피하는 구조``로 개선할 수 있을 것 같아요! 

[반복문 vs 재귀](https://woowacourse.github.io/javable/post/2020-04-30-iteration_vs_recursion/) 글을 보면 좋을 것 같아요~

2021-04-15 02:18 UTC, Rok93 commented on src/main/java/view/InputView.java
> +            return new Lotto(lottoNumbers);
제가 이야기하고자 하는 것은 inputLotto() 메서드로 받아오는 값은 원시 값인 String 타입 혹은 받아온 String 값을 List<Integer> (사실 List<Integer>은 원시 값이라 표현하기 그렇지만...)로 변환해주는 정도의 역할만 하는 것이 좋다는 뜻입니다. 

지금의 상태는 View가 ``LottoNumber``와 ``Lotto`` 도메인을 알고있기 때문에 Model과 View가 서로 의존성을 띈다고 볼 수 있습니다. 

조금 더 쉽게 얘기하면 여기서 stream으로 Integer을 LottoNumber로 변경하고  ``new Lotto(lottoNumbers)`` 해주는 행위를 Controller으로 옮기기만 하는 것입니다. 

이 외에 InputView의 내용들도 동일합니다. 리턴 타입이 바로 ``Model`` 이라면 동일한 피드백을 드릴 수 있을 것 같습니다.

2021-04-15 02:18 UTC, Rok93 commented on src/test/java/model/LottoNumberTest.java
> +                .hasMessage(LOTTO_NUMBER_MUST_BE_POSITIVE);
이렇게 1회성 테스트에 쓰이는 문자열은 그냥 하드코딩을 해도 괜찮을 것 같습니다.

2021-04-15 02:18 UTC, Rok93 commented on src/test/java/model/LottoNumberTest.java
> +                () -> assertThat(lottoNumber.getNumber()).isBetween(MIN_LOTTO_NUMBER, MAX_LOTTO_NUMBER),
바로 아래에 유효하지 않은 값 범위에 대한 LottoNumber 테스트가 진행되고 있는데, 이 코드는 굳이 테스트 할 필요가 있을까요?

2021-04-15 02:18 UTC, Rok93 commented on src/main/java/view/OutputView.java
> +    private static final String TOTAL_YIELD_IS = "총 수익률은 ";
아마 이전에 제가 피드백을 통해서 OutputView나 InputView의 출력 문자열들도 상수처리를 하는 모습을 보여드린 적이 있을 겁니다. 
저도 공부를 하면서 바뀌게 된 부분인데, ``이런 OutputView, InputView의 출력 문자와 모델에서 예외처리 메시지 의 경우에는 하드코딩을 하는 것도 괜찮다는 생각``입니다.  

자주 사용되고 그 의미를 파악하기 힘든 경우 하드코딩하는 것 보다 상수처리를 하여 그 의미도 명확하게 하고 자주 사용하기 때문에 미리 static  메모리에 올려두고 사용하는 것이 더 효율적일 수 있지만, 예외처리나 단순한 출력문자열의 경우 ``자주 사용된다``, ``의미를 파악하기 힘들다`` 이 두 가지 경우에 모두 해당하지 않는다는 것을 알 수 있습니다.  따라서 꼭 이런 문자열들을 상수로 처리할 필요가 없다고 제 생각이 바뀌게 되었습니다.  재홍님도 이 부분에 대해서는 한번 고민해보시면 좋을 것 같아요!  

꼭 바꾸라는 이야기가 아니라 선택의 영역이 될 것 같습니다. (이미 이번 미션에서는 전체적으로 상수로 추출하는 구조로 짜셨기 때문에 굳이 변경하실 필요는 없습니다  😁)

2021-04-15 02:18 UTC, Rok93 commented on src/test/java/model/LottoNumberTest.java
> +        assertThat(lottoNumber.getNumber()).isBetween(MIN_LOTTO_NUMBER, MAX_LOTTO_NUMBER);
테스트 코드의 경우 특히나 번거롭게 상수 추출을 하지 않으셔도 될 것 같습니다.

2021-04-15 02:18 UTC, Rok93 commented on src/main/java/model/Lottos.java
> +        Map<Rank, Integer> statistics = produceStatistics(winningLotto);
main 함수에서 
```java
    Map<Rank, Integer> statistics = lottos.produceStatistics(winningLotto);
    double yield = lottos.calculateYield(winningLotto, money);
```
와 같이 호출되고 있어요! 
calculateYield 메서드를 보면 ``produceStatistics()``  메서드가 두 번 연속으로 호출되고 있음을 알 수 있어요! 
``produceStatistics()`` 을 통해 얻은 결과가 있어야 calculateYield() 기능을 수행할 수 있다고 생각되네요! 
이런 경우 같은 기능을 두 번 호출하는 것 보다는 ``Map<Rank, Integer> statistics`` 을 필드로 가지는 ``LottoResults`` 일급 컬렉션을 만들어 보는건 어떤가요?  ``produceStatistics()`` 기능의 리턴 값으로 이 일급 컬렉션을 반환하는 건 어떨까요?

2021-04-15 02:18 UTC, Rok93 commented on src/main/java/model/Lottos.java
> +    public List<Lotto> getLottos() {
getter 위치!

2021-04-15 02:18 UTC, Rok93 commented on src/main/java/model/Money.java
> +        if (isNegativeAmount) {
약간 과할 수도 있는 리뷰일 수 있으나, 저라면 이렇게 변경했을 거 같아요! 
```suggestion
        int status = amount.compareTo(BigDecimal.ZERO);
        if (status  == IS_NEGATIVE) {
```

2021-04-15 02:18 UTC, Rok93 commented on src/main/java/model/NumberGenerator.java
> +public interface NumberGenerator {
``NumberGenerator``와 이 구현체들은 제가 의도했던 바와는 많이 다릅니다. 
사실 이번 미션에서 만들고 싶은 것은 RandomNumber가 아니라 Random Lotto 혹은 Lottos 입니다. 
``NumberGenerator``을 만들기보다는 ``LottoGenerator``를 만드는 것이 저의 의도입니다. 

지금와서보니 부족한 점도 많지만, 이해를 돕기위해 제가 이전에 구현한 코드를 공유드립니다. 

[Lottos 코드](https://github.com/Rok93/selft-java-lotto/blob/master/src/main/java/domain/Lottos.java)
[LottoGenerator](https://github.com/Rok93/selft-java-lotto/blob/master/src/main/java/domain/LottoGenerator.java) 
[Lottos 테스트 코드](https://github.com/Rok93/selft-java-lotto/blob/master/src/test/java/domain/LottosTest.java)

2021-04-15 02:18 UTC, Rok93 commented on src/main/java/model/Rank.java
> +    FIRST(6, new Money(new BigDecimal(2000000000))),
```suggestion
    FIRST(6, new Money(new BigDecimal(2_000_000_000))),
```
숫자형의 경우 이런식으로 ``_``을 추가해도 동일한 값으로 봅니다. 
코드의 가독성을 높이는데 도움이 되겠죠!? 😉

2021-04-16 09:08 UTC, banjjoknim commented on src/main/java/model/Lotto.java
> +            List<LottoNumber> lottoNumbers = Stream.generate(() -> numberGenerator.generate())
좋은 피드백 감사합니다. 반영하도록 하겠습니다.

2021-04-16 13:56 UTC, banjjoknim commented on src/main/java/model/Lotto.java
> +    public static final BigDecimal LOTTO_PRICE = new BigDecimal(1000);
놓쳤던 부분인 것 같습니다. 반영하도록 하겠습니다.

2021-04-16 13:59 UTC, banjjoknim commented on src/test/java/model/LottoNumberTest.java
> +                .hasMessage(LOTTO_NUMBER_MUST_BE_POSITIVE);
유념하도록 하겠습니다.

2021-04-16 14:16 UTC, banjjoknim commented on src/test/java/model/LottoNumberTest.java
> +                () -> assertThat(lottoNumber.getNumber()).isBetween(MIN_LOTTO_NUMBER, MAX_LOTTO_NUMBER),
유효하지 않은 값 범위에 대한 테스트를 하는 것 처럼, 유효한 값 범위에 대한 테스트 또한 명확히 해야한다고 생각하기에 테스트를 작성하였습니다. 이 부분에 대해서는 어떻게 생각하시나요?

2021-04-16 14:20 UTC, banjjoknim commented on src/main/java/model/Lottos.java
> +    public List<Lotto> getLottos() {
놓쳤던 부분인 것 같습니다. 주의하도록 하겠습니다.

2021-04-16 14:23 UTC, banjjoknim commented on src/main/java/model/Money.java
> +        if (isNegativeAmount) {
좀 더 가독성이 좋아진 것 같습니다. 감사합니다.

2021-04-16 14:51 UTC, banjjoknim commented on src/main/java/view/InputView.java
> +            return new Lotto(lottoNumbers);
좋은 답변 감사드립니다. 많은 도움이 되었습니다.

2021-04-16 14:57 UTC, banjjoknim commented on src/main/java/model/Rank.java
> +    FIRST(6, new Money(new BigDecimal(2000000000))),
피드백 감사합니다. 유념하도록 하겠습니다.

2021-04-17 01:09 UTC, banjjoknim commented on src/main/java/model/LottoNumber.java
> +    }
사실 처음에는 보여주신 참고자료처럼 코드를 작성했었습니다. 그러다, 처음부터 객체를 전부 저장해놓고 시작하는 것은 결국 상수가 아닐까? 라는 생각에 코드를 수정하여 제출했습니다. 캐싱을 한다는 것은 저장해둔다의 의미도 갖지만 말씀해주신대로 할 경우, 만약 로또 정책이 변경되어 로또 번호가 엄청나게 많아진다면 처음부터 로또 번호를 전부 저장해놓는 것 또한 메모리 낭비가 심할 것이라 생각되었습니다. 이러한 경우를 고려하다보니, 실제 사용한 객체만 캐시에 저장하도록 구현했는데, 이 부분에 대해서는 어떻게 생각하시나요?

2021-04-17 04:51 UTC, banjjoknim commented on src/main/java/model/NumberGenerator.java
> +public interface NumberGenerator {
미션의 목표에 맞게끔 전략을 설정하라는 말씀 감사합니다. 고민하여 반영하도록 하겠습니다.

2021-04-17 04:51 UTC, banjjoknim commented on src/main/java/model/Lotto.java
> +        }
좋은 참고자료 감사합니다! 참고하여 반영해보도록 하겠습니다!

2021-04-17 04:53 UTC, banjjoknim commented on src/main/java/model/Lottos.java
> +        Map<Rank, Integer> statistics = produceStatistics(winningLotto);
좋은 방향성 제시 감사드립니다! 고민하여 반영해보도록 하겠습니다!

2021-04-17 06:01 UTC, banjjoknim commented
지난 피드백을 잘 반영하도록 노력했는데, 잘 되었는지 모르겠네요 😂
꼼꼼히 봐주셔서 감사합니다.

피드백을 반영하는 과정에서 궁금한 점이 생겨 질문 드립니다.

---
1. `캐싱(caching)`

>[해당 코멘트](https://github.com/banjjoknim/java-lotto-game/pull/2#discussion_r613224437)
>
>사실 처음에는 보여주신 참고자료처럼 코드를 작성했었습니다-[작성했던 코드](https://github.com/banjjoknim/java-lotto-game/pull/2/commits/a9a5e9f52cf6243c972053c996d9f4b79dca6d3a)-(이미 해당 참고자료를 접했었네요 하하..). 캐시에 저장된 데이터를 가져올 때, 먼저 캐시에 있는지 없는지 조회를 하는 것으로 알고 있는데 이때, 처음부터 객체를 전부 저장해놓고 시작하는 것은 결국 상수가 아닐까? 라는 생각에 코드를 수정하여 제출했습니다.
>
>캐싱을 한다는 것은 저장해둔다의 의미도 갖지만 말씀해주신대로 할 경우, 만약 로또 정책이 변경되어 로또 번호가 엄청나게 많아진다면 처음부터 로또 번호를 전부 저장해놓는 것은 메모리 낭비가 심할 것이라 생각되었습니다. 이러한 경우를 고려하다보니, 캐시를 조회해서 데이터가 존재하지 않으면 캐시에 저장한뒤(`putIfAbsent`) 가져오고, 데이터가 존재한다면 바로 가져오도록 구현했는데, 이 부분에 대해서는 어떻게 생각하시나요?

---

2. `InputView`

>[해당 코멘트](https://github.com/banjjoknim/java-lotto-game/pull/2#discussion_r613664458)
>
>피드백을 반영하는 과정에서, 컨트롤러에서 `List<Integer> -> List<LottoNumber>`의 변환과정을 처리해주는 객체가 따로 필요한 것인지 많은 고민이 되었습니다. 하지만 `Lotto` 자체에서 `List<LottoNumber>` 를 갖고 있기 때문에, 새롭게 객체를 만드는 것도, `Lotto` 객체에서 해당 변환을 처리하는 것도 어색하다고 느껴져서 말씀해주신 것처럼 컨트롤러에서 바로 처리하도록 하였습니다. 이렇게 되면 컨트롤러에서 입력값에 대한 검증과 변환등의 작업을 모두 처리하게 되는데, 이렇게 하는 것이 책임을 제대로 분리한 것인지(?) 확신이 서지 않아서 이 부분에 대해 제가 한 부분이 잘된 것인지, 그리고 이 부분에 대해서 어떻게 생각하시는지 궁금합니다.

---

3. `테스트의 범위`

>[해당 코멘트](https://github.com/banjjoknim/java-lotto-game/pull/2#discussion_r613669557)
>
>유효하지 않은 값의 범위에 대한 테스트가 있기 때문에 유효한 값에 대한 테스트를 궅이 할 필요가 있냐고 하셨는데, 좀 더 구체적이고 확실하게 테스트를 하기 위해선 필요하다고 생각했었습니다. 이 부분에 대해서는 어떻게 생각하시나요?

---

이상입니다. 늘 감사드립니다 😄

2021-04-19 15:06 UTC, Rok93 commented on src/main/java/model/Lotto.java
> +        if (lottoNumbersSize != LOTTO_SIZE) {
``new HashSet<>(numbers)``가 더 명확한 의미를 띄도록 변경해주는 것이 좋을 것 같아요. 
Set 자료구조를 통해서``중복을 제거하려고 했던 의도``를 더 잘 드러내주는 변수명이면 더 좋을 것 같아요.

2021-04-19 15:06 UTC, Rok93 commented on src/main/java/model/Lotto.java
> +
```suggestion
```
불필요한 들여쓰기인 것 같아요~

2021-04-19 15:06 UTC, Rok93 commented on src/main/java/model/NumberGenerator.java
> +public interface NumberGenerator {
``LottoGenerator`` 가 있으므로 ``NumberGenerator`` 인터페이스와 구현체들은 불필요하다고 느껴집니다. 

제가 의도한 것은 ``RandomNumberGenerator``를 따로 구현할 필요 없이, ``AutoLottoGenerator`` 에서 RandomNumber를 생성하는 랜덤 함수를 통해 직접  Random Lotto를 바로 만드는 것을 의도한 것입니다. 
그렇게되면, 로또를 발급하는 기능인 Lottos의 ``issueLottos``는 파라미터로 ``LottoGenerator`` 인터페이스를 받을 것입니다. issueLottos는 인터페이스이기 때문에 추상 클래스를 구현하거나 혹은 [함수형 인터페이스](https://woowacourse.github.io/javable/post/2020-07-17-Functional-Interface/)인 경우에는 ``람다식``으로 LottoGernerator의 메서드를 호출하였을 때, 얻게되는 결과 값을 컨트롤할 수 있게 됩니다. 

### ex) 익명 클래스로 결과 값 컨트롤 
```java
Lottos.issueLottos(money, new LottoGenerator() {
            @Override
            public Lotto generate(NumberGenerator numberGenerator) {
                return new Lotto(Collections.emptyList());
            }
        });
```

### ex) 람다식을 이용한 결과 값 컨트롤
``issueLottos(money, () -> new Lotto(1, 2, 3, 4, 5, 6));`` 
LottoGernerator의 generate를 호출하면 **new Lotto(1, 2, 3, 4, 5, 6)** 로또가 반환될 수 있다는 것을 예상할 수 있습니다. 

``값을 원하는대로 조작``할 수 있기 때문에 결과 값을 예상할 수 있고, 따라서 결괏값 또한 예상할 수 있어 ``테스트 코드를 작성하는 것도 가능해지는 것``입니다.

2021-04-19 15:06 UTC, Rok93 commented on src/main/java/model/LottoGenerator.java
> +public interface LottoGenerator {
이와 같이 ``추상 메서드가 단 하나 뿐인 인터페이스``를 함수형 인터페이스라고 부릅니다. 
그리고 이런 함수형 인터페이스는 `@FunctionalInterface` 애너테이션을 붙입니다. (이 애너테이션의 역할에 대해서는 추상메서드를 하나 더 추가해보면 금방 알 수 있을 것 같아요~ 😉) 

```suggestion
@FunctionalInterface
public interface LottoGenerator {
```

2021-04-19 15:06 UTC, Rok93 commented on src/test/java/model/LottoNumberTest.java
> +    }
테스트 메서드명이나 DisplayName을 봤을 때, 이 테스트는 RandomNumberGenerator 구현체를 테스트하기 위한 용도로 보입니다. 
하지만 지금 테스트는 구현체를 테스트한다기보다는 오히려 ``createLottoNumberTest``와 동일한 테스트를 하고 있는 것 처럼 보입니다. 

테스트를 굳이 한다면,  ``RandomNumberGeneratorTest`` 테스트 클래스에서 LottoNumber 없이 ``strategy.generate()``의 결과에 대한 테스트를 하는게 좋지 않을까 싶어요! 🤔

2021-04-19 15:06 UTC, Rok93 commented on src/test/java/model/LottoNumberTest.java
> +                () -> assertThat(lottoNumber.getNumber()).isBetween(MIN_LOTTO_NUMBER, MAX_LOTTO_NUMBER),
이 테스트 코드는 
1. 특정 범위내에 있다! 라는 테스트는 될 수 있지만, 그 값이 어떤 값인지 정확히 파악할 수는 없습니다. 테스트를 매번 실행할 때 마다 해당 테스트는 분명 통과하겠지만, 정확히 어떤 값이 나올지에 대해서는 예측할 수 없습니다. 테스트 코드는 input에 대한 정확한 output을 검증하기 위한 용도로 사용해야한다고 생각합니다. 즉 특정 입력에 대해서 결과값을 예측할 수 있어야한다는 의미입니다(``LottoGenerator``와 같은 인터페이스를 만든 것도 이 것과 연관되어 있습니다). 

2. 이 테스트 코드가 LottoNumber를 테스트하는 것인지에 대해 고민해볼 필요가 있습니다. 제가 보기에는 사실상 그냥 ``Random Number``를 생성하는 기능으로 보이기에 Random Number를 생성하는 그 행위 자체를 테스트를 하는 것이 더 나아보입니다. (물론 하더라도 앞의 문제를 피하지는 못할거에요)

제가 드렸던 피드백에서 빠진 내용이 있네요. 
LottoNumberTest 테스트 클래스 내부에 ``유효하지 않은 범위에 대한 테스트``도 있지만, ``유효한 범위에서의 테스트``(createLottoNumberTest)도 있습니다. LottoNumber 객체의 value 값에 대한 유효성 검증은 이미 충분하다고 느껴집니다. 

> 바로 아래에 유효하지 않은 값 범위에 대한 LottoNumber 테스트가 진행되고 있는데, 이 코드는 굳이 테스트 할 필요가 있을까요?

위의 코멘트를 남긴 이유입니다(리뷰를 남기고 몇일이 지나고 저도 워낙 많은 피드백을 받고있는 입장이다보니 리뷰를 남길 때 제가 정확히 어떤 생각을 하고 올렸는지 저도 정확히는 기억이 안나네요 😅).

2021-04-19 16:09 UTC, Rok93 requested changes
세 가지 질문을 해주셨는데요. 하나씩 답변을 드려보고자 합니다. 

> 1. 캐싱 
> 사실 처음에는 보여주신 참고자료처럼 코드를 작성했었습니다-작성했던 코드-(이미 해당 참고자료를 접했었네요 하하..). 캐시에 저장된 데이터를 가져올 때, 먼저 캐시에 있는지 없는지 조회를 하는 것으로 알고 있는데 이때, 처음부터 객체를 전부 저장해놓고 시작하는 것은 결국 상수가 아닐까? 라는 생각에 코드를 수정하여 제출했습니다. 캐싱을 한다는 것은 저장해둔다의 의미도 갖지만 말씀해주신대로 할 경우, 만약 로또 정책이 변경되어 로또 번호가 엄청나게 많아진다면 처음부터 로또 번호를 전부 저장해놓는 것은 메모리 낭비가 심할 것이라 생각되었습니다. 이러한 경우를 고려하다보니, 캐시를 조회해서 데이터가 존재하지 않으면 캐시에 저장한뒤(putIfAbsent) 가져오고, 데이터가 존재한다면 바로 가져오도록 구현했는데, 이 부분에 대해서는 어떻게 생각하시나요?

``캐싱``은 ``트레이드오프`` ⚖️ 라고 생각합니다. 실제로 캐싱에서는 ``캐시 히트``를 늘리는(= ``캐시 미스``를 줄이는) 것이 중요합니다. [참고 자료 ](https://blog.naver.com/PostView.nhn?blogId=cjsksk3113&logNo=222290234374&parentCategoryNo=&categoryNo=&viewDate=&isShowPopularPosts=false&from=postView)  (꼭 안봐도 상관없으나 관심있으실까봐 첨부합니다)  

당연히 로또 번호가 엄청나게 많아져서 메모리에 부담이 될 정도라면 캐싱을 하는 것을 포기하던지 일부만 캐싱을 한다거나 하는 다른 대안을 찾아야할 것입니다. 하지만 지금 로또 미션의 경우 로또 번호의 수가 1~45로 고정된다는 사실이 명확하기도 하고 🤔, 로또 번호가 아무리 늘어나봐야 이런 걱정을 할 정도로 늘지는 않을 것이라 생각합니다 😉. (~~너무 극단적인 경우를 미리 고려한다고 생각해야할까요...?~~) 

그리고 여기서 캐싱을 하는 이유는 사실 오버헤드를 줄이기 위한 용도가 가장 큽니다. LottoNumber 객체를 미리 캐싱해둠으로써 매번 LottoNumber 객체를 생성하는 

> 2. InputView
> 피드백을 반영하는 과정에서, 컨트롤러에서 List<Integer> -> List<LottoNumber>의 변환과정을 처리해주는 객체가 따로 필요한 것인지 많은 고민이 되었습니다. 하지만 Lotto 자체에서 List<LottoNumber> 를 갖고 있기 때문에, 새롭게 객체를 만드는 것도, Lotto 객체에서 해당 변환을 처리하는 것도 어색하다고 느껴져서 말씀해주신 것처럼 컨트롤러에서 바로 처리하도록 하였습니다. 이렇게 되면 컨트롤러에서 입력값에 대한 검증과 변환등의 작업을 모두 처리하게 되는데, 이렇게 하는 것이 책임을 제대로 분리한 것인지(?) 확신이 서지 않아서 이 부분에 대해 제가 한 부분이 잘된 것인지, 그리고 이 부분에 대해서 어떻게 생각하시는지 궁금합니다. 

MVC의 각 요소의 역할을 생각했을 때,``M``과 ``V``는 ``서로를 몰라야 한다``는 관점에서 Lotto객체가 해당 변환을 처리하는 것은 어색하다는 것은 이해를 하셨을 것 같아요~! 또한 ``C``는 M과 V를 연결해주는 역할이기 때문에 Controller에서 이 변환을 처리해주는 것이 더 적합하다고 생각할 수 있을 것 같아요. 

실제 스프링 프로젝트에서도 뷰에서 입력받은 값을 스프링이 DTO객체로 파싱 해주고, @Valid or @Validated 와 같은 애너테이션으로 입력 값을 검증할 수 있습니다. 

이 부분은 이전에 제가 받았던 [이 피드백](https://github.com/woowacourse/java-lotto/pull/333#discussion_r584541596)을 참고해보면 좋을 것 같아요.  (사실 제가 이미 드렸던 피드백에 다 포함이 되는 것 같아요 🤔) 

> 3. 테스트의 범위
> 유효하지 않은 값의 범위에 대한 테스트가 있기 때문에 유효한 값에 대한 테스트를 궅이 할 필요가 있냐고 하셨는데, 좀 더 구체적이고 확실하게 테스트를 하기 위해선 필요하다고 생각했었습니다. 이 부분에 대해서는 어떻게 생각하시나요?

이 부분에 대해서는 이미 다른 테스트가 충분히 LottoNumber의 유효성을 검증해준다고 생각하고, 해당 테스트는 LottoNumber를 테스트하는 것이 아니라 ``NumberGenerator`` 를 테스트하고 싶은 기능이라 생각한다고 생각합니다. (해당 코멘트에 추가 코멘트 달아뒀으니 더 자세한 답변은 코멘트 확인 부탁드려요 👀)

2021-04-20 03:04 UTC, banjjoknim commented on src/main/java/model/Lotto.java
> +        if (lottoNumbersSize != LOTTO_SIZE) {
좋은 피드백 감사합니다. 반영하도록 하겠습니다!

2021-04-20 03:07 UTC, banjjoknim commented on src/main/java/model/LottoGenerator.java
> +public interface LottoGenerator {
놓쳤던 부분인 것 같습니다. 감사합니다.

2021-04-20 16:16 UTC, banjjoknim commented
리뷰어님 안녕하세요?
점점 적어지는 코멘트들을 보며 이번 미션도 막바지에 이르고있는 것 같다는 생각이 듭니다.
피드백들을 반영하려고 노력하였는데 잘 되었는지 모르겠습니다.

이번에도 역시 질문이 있습니다.

1. `LottoGeneratorTest`
> [해당 코멘트](https://github.com/banjjoknim/java-lotto-game/pull/2#discussion_r615808835)
>
>코멘트에 대해서 이해한 뒤, `LottoGenerator` 인터페이스에 대한 테스트를 작성하면서 궁금증이 생겼습니다. 익명 클래스를 이용한 결과 값 컨트롤, 람다식을 이용한 결과 값 컨트롤 등 구현체를 직접 제공함으로써 결과값을 조작할 수 있고 이를 통해 테스트를 할 수 있다고 하셨습니다. 해당 코멘트에 대해서는 이해했으나, `LottoGenerator`의 역할은 결국 `Lotto`를 생성하는 것이기 때문에 굳이 새로운 구현체를 추가해서 구현체에 대한 테스트를 작성해야하는지 궁금합니다(예를 들어, 중복된 번호로 로또를 생성하는 구현체라던지, 범위 밖의 번호로 로또를 생성하는 구현체라던지...). 이미 `LottoTest`에 해당 구현체의 결과물(중복된 숫자 예외 처리, 범위 밖 숫자 예외 처리)에 대한 테스트가 작성되어 있기 때문입니다. 그래서 현재는 `AutoLottoGenerator`에 대한 테스트만 작성했는데 괜찮은걸까요?

이상입니다! 꼼꼼한 리뷰 감사드립니다!

2021-04-21 05:21 UTC, Rok93 approved these changes
마지막으로 Money 와  질문남겨주신 내용에 대한 피드백 남겼습니다. 
이번 미션은 여기서 종료해도 괜찮을 것 같네요 😉
그 동안 고생 많으셨어요. 이제 다음 미션에서 뵐게요 🙇‍♂️

피드백 남긴 내용들에 대해서는 확실하게 이해하고 넘어가야할 것 같아요.
테스트 코드 관련 내용은 꼭 수정을 해주시고 Money 관련 피드백은 가볍게 읽어만 봐주세요 : )
궁금한 점이 있으면 DM이나 개인적으로 연락 주세요!

2021-04-21 05:21 UTC, Rok93 commented on src/main/java/controller/LottoGame.java
> +                .map(LottoNumber::new)
```suggestion
                .map(LottoNumber::getLottoNumberFromCache)
```

2021-04-21 05:21 UTC, Rok93 commented on src/main/java/model/LottoNumber.java
> +    public LottoNumber(int number) {
```suggestion
    private LottoNumber(int number) {
```

LottoNumber를 캐싱했기 때문에 외부에서는 생성자로 LottoNumber를 새로 생성하는 것이 아닌 ``getLottoNumberFromCache``로 캐싱 값을 가져오도록 변경하는 것이 좋을 것 같아요. 생성자를 public으로 열어두는 것 보다는 private로 외부에서 사용하지 못하게 닫아두는 것이 의도한대로 LottoNumber를 사용하도록 강제할 수 있어요.

2021-04-21 05:21 UTC, Rok93 commented on src/main/java/model/LottoNumber.java
> +    public static LottoNumber getLottoNumberFromCache(int number) {
개인적으로 ``getter`` 의 네이밍을 별로 좋아하지는 않아요. 또한 이 메서드는 ``정적 팩토리 메서드`` 인데, [참고 자료](https://www.slipp.net/wiki/pages/viewpage.action?pageId=30771479) 에서 **정적 팩터리 메서드에 흔히 사용하는 명명 방식**을 참고해서 네이밍을 해보면 좋을 것 같아요!!

2021-04-21 05:21 UTC, Rok93 commented on src/main/java/model/LottoStatistics.java
> +        return totalBenefit.divide(totalSpendMoney, YIELD_SCALE, RoundingMode.HALF_EVEN).doubleValue();
이 코드도 엄밀하게 생각하면 Money 내부의 BigDecimal 값들을 꺼내서 외부에서 계산을 하고 있는 것 처럼 보이네요 : )
이 또한 Money 객체에 메시지를 보내는 방식으로 변경할 수 있을 것 같아요 ~!

2021-04-21 05:21 UTC, Rok93 commented on src/main/java/model/LottoStatistics.java
> +    }
이 또한 Rank 의 winningMoney 가 ``Money`` 타입이기 때문에 아래와 같이 변경해볼 수도 있을 것 같네요 😉

```suggestion
    private BigDecimal calculateTotalBenefit(Map<Rank, Integer> statistics) {
        return Arrays.stream(Rank.values())
                .map(rank -> rank.calculateBenefit(statistics.get(rank)))
                .reduce(BigDecimal.ZERO, (previousBenefit, nextBenefit) -> previousBenefit.add(nextBenefit));
    }
```

2021-04-21 05:21 UTC, Rok93 commented on src/main/java/model/Money.java
> +    }
Money 객체를 불변객체로 만들고 싶은 의도로 보여요 : ) 
지금 Money의 연산 기능들의 반환 타입은 자기 자신과 같은 타입이어야 한다고 생각해요. 
또한 Money는 VO 객체로 볼 수 있을 것 같네요 : ) 
VO 객체에 대한 피드백은 이전에 드렸기 때문에 Money 객체가 VO 객체로 만드려면 어떻게 처리할 수 있을지에 대해 고민해볼 수 있을 것 같아요. 

지금은 변경해야 할 것들이 너무 많아지기 때문에 변경하지 않아도 괜찮지만 

[불변객체를 만드는 방법](https://woowacourse.github.io/javable/post/2020-05-18-immutable-object/) <br> 
JPA를 사용해본적이 있으시니(~~Entity가 꼭 JPA만 해당하는 개념은 아니지만..~~) 해당 글을 읽어보는 것도 좋을 것같아요! [DTO vs VO vs Entity](https://jordy-torvalds.tistory.com/81)  


```suggestion
    public Money calculateTotalSpendMoney() {
        BigDecimal spendMoney = amount.remainder(LOTTO_PRICE);
        return new Money(amount.subtract(spendMoney));
    }

    public Money multiplyCount(int winningCount) {
        BigDecimal winningCountNumber = new BigDecimal(winningCount);
        return new Money(amount.multiply(winningCountNumber));
    }
```

2021-04-21 05:21 UTC, Rok93 commented on src/main/java/controller/LottoGame.java
> +        Lottos lottos = Lottos.issueLottos(money, new AutoLottoGenerator());
> 코멘트에 대해서 이해한 뒤, LottoGenerator 인터페이스에 대한 테스트를 작성하면서 궁금증이 생겼습니다. 익명 클래스를 이용한 결과 값 컨트롤, 람다식을 이용한 결과 값 컨트롤 등 구현체를 직접 제공함으로써 결과값을 조작할 수 있고 이를 통해 테스트를 할 수 있다고 하셨습니다. 해당 코멘트에 대해서는 이해했으나, LottoGenerator의 역할은 결국 Lotto를 생성하는 것이기 때문에 굳이 새로운 구현체를 추가해서 구현체에 대한 테스트를 작성해야하는지 궁금합니다(예를 들어, 중복된 번호로 로또를 생성하는 구현체라던지, 범위 밖의 번호로 로또를 생성하는 구현체라던지...). 이미 LottoTest에 해당 구현체의 결과물(중복된 숫자 예외 처리, 범위 밖 숫자 예외 처리)에 대한 테스트가 작성되어 있기 때문입니다. 그래서 현재는 AutoLottoGenerator에 대한 테스트만 작성했는데 괜찮은걸까요? 

위와 같은 질문을 주셨는데, 저의 의도는 ``LottoGenerator``를 테스트하자는 것이 아닌, `테스트하기 힘든 코드를 분리하자``는 것이었고, 그 방법이 ``interface``로 Random 로직을 분리해내는 것이었습니다. 전에 전달드렸던 용근님의 발표 내용이 테스트하기 힘든 코드를 외부로 꺼내서 테스트 영역을 확보해나가라는 메시지를 전달하고 있습니다. 

LottoGenerator 인터페이스를 통해서  테스트하기 힘들었던 ``Lottos#issueLottos``를 테스트하기 쉬운 코드로 만들었습니다. 
흐름이 조금 이해가 되실지 모르겠네요 🤔 

결국 지금까지 코드를 리팩토링해왔던 이유는 LottoGenerator의 구현체인 ``AutoLottoGenerator``의 **테스트 코드를 작성하기위한 것이 아닌**  ``Lottos#issueLottos`` 를 정확하게 테스트하는 것이 목표였고 그런 방향으로 리팩토링 해왔던 것입니다.  
지난번에 피드백드렸던 [내용](https://github.com/banjjoknim/java-lotto-game/pull/2#discussion_r615808835) 이와 관련되서 테스트를 어떻게 작성해야하는지 구체적으로 보여드린 예시라 생각하시면 됩니다.  

구현체에 대한 테스트는 조금은 자율에 맡길 수 있지 않을까 싶습니다.

2021-04-21 05:21 UTC, Rok93 commented on src/main/java/controller/LottoGame.java
> +        return new LottoNumber(number);
마찬가지로 캐싱을 했는데 막상 그 값을 사용하고 있지는 않네요. 
이것이 생성자를 public으로 뒀기 때문이라고 볼 수 있겠죠? 😉
```suggestion
        return LottoNumber.getLottoNumberFromCache(number);
```

2021-04-21 13:33 UTC, banjjoknim commented on src/main/java/controller/LottoGame.java
> +                .map(LottoNumber::new)
놓쳤던 부분인데, 감사합니다.

2021-04-21 13:34 UTC, banjjoknim commented on src/main/java/model/LottoNumber.java
> +    public LottoNumber(int number) {
생각지도 못한 부분인 것 같습니다. 피드백 감사합니다.

2021-04-21 13:36 UTC, banjjoknim commented on src/main/java/controller/LottoGame.java
> +        return new LottoNumber(number);
감사합니다!

2021-04-21 13:44 UTC, banjjoknim commented on src/main/java/model/LottoNumber.java
> +    public static LottoNumber getLottoNumberFromCache(int number) {
참고 자료 감사합니다! 반영하도록 하겠습니다.

2021-04-21 14:08 UTC, banjjoknim commented on src/main/java/model/LottoStatistics.java
> +        return totalBenefit.divide(totalSpendMoney, YIELD_SCALE, RoundingMode.HALF_EVEN).doubleValue();
좋은 피드백 감사드립니다. 반영하도록 하겠습니다.

2021-04-21 14:34 UTC, banjjoknim commented on src/main/java/controller/LottoGame.java
> +        Lottos lottos = Lottos.issueLottos(money, new AutoLottoGenerator());
좋은 피드백 감사합니다. 다소 어렵게 느껴지는 건 사실이지만 유념하여 이후의 코드에 적용할 수 있도록 해보겠습니다!

2021-04-21 15:17 UTC, banjjoknim commented on src/main/java/model/Money.java
> +    }
Money 객체가 연산을 했을 때 반환 타입이 Money여야 한다는 의미가 이해가 잘 되지 않는 것 같습니다. 고민해보는 시간을 가져보도록 하겠습니다. 감사합니다.

2021-04-21 16:22 UTC, merged